<a href="https://colab.research.google.com/github/Sauvi72/Data_sci_Python/blob/main/lec_07_pandas_%7C%7C%7C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
import pandas as pd

df = pd.read_csv('student_data.csv')

In [5]:
#groupby('kiske sath karna chahte ho')['kis pe karna chahte ho'].agg('konsa fn perform karna hai')

df.groupby('placement_status')['placement_status'].agg('count')

placement_status
Not Placed    1644
Placed        8356
Name: placement_status, dtype: int64

In [8]:
df.groupby('placement_status')['exam_score'].agg('mean')

placement_status
Not Placed    59.804653
Placed        91.996556
Name: exam_score, dtype: float64

In [9]:
df.groupby('placement_status')['study_hours'].agg('mean')

placement_status
Not Placed    3.130170
Placed        6.552178
Name: study_hours, dtype: float64

In [11]:
#catagorical and numerical data
# | -> groupby('catagorical data [numerical data]
# | ->
# |
# |
# |

In [17]:
def grades(score):
  if score >= 90:
    return 'A'
  elif score >= 80:
    return 'B'
  elif score >= 70:
    return 'C'
  elif score >= 60:
    return 'D'
  else:
    return 'F'


df['grade'] = df['exam_score'].apply(grades)
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,grade
0,7,56,8,7,10,62,100.00,Placed,A
1,4,69,5,3,8,56,100.00,Placed,A
2,11,60,7,6,10,45,100.00,Placed,A
3,8,99,9,8,4,55,90.17,Placed,A
4,5,52,8,6,8,40,78.82,Placed,C
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,D
9996,7,98,6,9,4,87,100.00,Placed,A
9997,10,44,8,5,10,37,95.94,Placed,A
9998,10,75,7,5,8,52,88.61,Placed,B
9999,2,70,6,11,16,52,78.96,Placed,C